update Dockerfile and build script(s) to Ubunto 22.04

diff --git a/deployment/docker/Dockerfile b/deployment/docker/Dockerfile
--- a/deployment/docker/Dockerfile
+++ b/deployment/docker/Dockerfile
@@ -1,86 +1,69 @@
 FROM ubuntu:22.04
 LABEL maintainer="Form.io <support@form.io>"
 
-# Install dependencies
-RUN apt-get update \
-    && apt-get install \
-    cmake \
-    ttf-freefont \
-    gnu-libiconv-dev \
-    libvpx \
-    dumb-init \
-    git \
+# Set initial environment variables
+ENV PDF2HTMLEX_URL=https://github.com/pdf2htmlEX/pdf2htmlEX/releases/download/v0.18.8.rc1/pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-focal-x86_64.deb \
+    PDF2HTMLEX=pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-focal-x86_64.deb \
+    DEBIAN_FRONTEND=noninteractive
+
+# Install dependencies, fonts, chromium, and pdf2htmlEX
+RUN apt-get update && \
+    # Dependencies
+    apt-get install -y \
+    gnupg \
     wget \
-    nghttp2 \
-    nghttp2-libs \
-    libxslt \
-    libass \
-    cairo \
-    libcairo-dev \
-    libpng-dev \
-    libjpeg-dev \
-    libxml2-dev \
-    libx11 \
-    ghostscript \
-    poppler-data \
-    poppler-utils \
-    gettext \
-    build-base \
-    poppler \
-    qt5-qtbase \
-    qt5-qtbase-dev \
-    poppler-qt5 \
-    poppler-dev \
-    poppler-qt5-dev \
-    yarn \
-    && rm -rf /var/lib/apt/lists/* \
-    && rm /var/cache/apk/*
-
-RUN npm update -g npm
-
-# Install fonts
-RUN apk add --no-cache msttcorefonts-installer fontconfig \
-    && update-ms-fonts \
-    && wget https://github.com/google/fonts/archive/main.tar.gz -O gf.tar.gz \
-    && tar -xf gf.tar.gz \
-    && mkdir -p /usr/share/fonts/truetype/google-fonts \
-    && find ./fonts-main/ -name "*.ttf" -exec install -m644 {} /usr/share/fonts/truetype/google-fonts/ \; || return 1 \
-    && rm -f gf.tar.gz \
-    && rm -rf /fonts-main
+    curl \
+    g++ \
+    cmake \
+    make \
+    libpoppler-dev \
+    libpoppler-qt5-dev \
+    qtbase5-dev \
+    ghostscript && \
+    # Chromium
+    wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
+    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
+    apt-get update && \
+    apt-get install google-chrome-stable -y --no-install-recommends && \
+    rm -rf /var/lib/apt/lists/* && \
+    # pdf2htmlEX
+    wget "$PDF2HTMLEX_URL" && \
+    apt install -y --no-install-recommends ./$PDF2HTMLEX && \
+    # Disable EULA agreement for msttcorefonts
+    # echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections && \
+    # Fonts
+    # apt-get install -y ttf-mscorefonts-installer && \
+    # wget https://github.com/google/fonts/archive/main.tar.gz -O gf.tar.gz && \
+    # tar -xf gf.tar.gz && \
+    # mkdir -p /usr/share/fonts/truetype/google-fonts && \
+    # find ./fonts-main/ -name "*.ttf" -exec install -m644 {} /usr/share/fonts/truetype/google-fonts/ \; || return 1 && \
+    # Node.js and Yarn v1.x
+    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
+    apt-get install -y nodejs && \
+    npm install -g yarn && \
+    # Cleanup
+    apt-get clean && \
+    rm -f gf.tar.gz && \
+    rm -rf /fonts-main
 
 ENV APP_ROOT=/usr/src/pdf-libs
 WORKDIR $APP_ROOT
 
-# Building C++ tools
+# Build extract-formfields tool
 COPY cpp ./cpp
-## Building extract-formfields tool
 ARG EXTRACT_FORMFIELDS_ROOT=$APP_ROOT/cpp/extract-formfields
 WORKDIR $EXTRACT_FORMFIELDS_ROOT
 RUN ${EXTRACT_FORMFIELDS_ROOT}/build.sh
-ENV EXTRACT_FORMFIELDS=$EXTRACT_FORMFIELDS_ROOT/bin/extract-formfields
 
-## Building hide-formfields tool
-ARG HIDE_FORMFIELDS_ROOT=$APP_ROOT/cpp/hide-formfields
-WORKDIR $HIDE_FORMFIELDS_ROOT
-RUN ${HIDE_FORMFIELDS_ROOT}/build.sh
-ENV HIDE_FORMFIELDS=$HIDE_FORMFIELDS_ROOT/bin/hide-formfields
-# End building C++ tools
-
-# Installing third-party tools
-## Installing pdf2htmlEX
-WORKDIR /usr/src/pdf-libs
-RUN mkdir pdf2HtmlEx
-RUN wget https://github.com/pdf2htmlEX/pdf2htmlEX/releases/download/v0.18.8.rc1/pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-focal-x86_64.deb \
-    && apt -y upgrade && \
-    && apt -y --no-install-recommends install ./pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-focal-x86_64.deb \
-ENV PDF2HTMLEX_PATH="/usr/local/bin/pdf2htmlEX" \
+# Set runtime environment variables
+ENV EXTRACT_FORMFIELDS=$EXTRACT_FORMFIELDS_ROOT/bin/extract-formfields \
+    PDF2HTMLEX_PATH="/usr/local/bin/pdf2htmlEX" \
     PSTOPDF_PATH="/usr/bin/ps2pdf"
-# End installing third-party tools
 
 # Installing node.js packages
 COPY package.json ./
 COPY yarn.lock ./
-RUN yarn install --prod
+RUN yarn install --production
 
 # Adding sources
 COPY src ./src
